---
- hosts: host1
  remote_user: testadmin
  become_user: root
  gather_facts: no
  tasks:
  - name: Install nodejs
    apt: name=nodejs-legacy state=present
    become_user: root
  - name: Install npm
    apt: name=npm state=present
    become_user: root
  - name: Install Http-server
    shell: npm install http-server -g
    become_user: root
  - name: Straring Http-server
    shell: http-server ~/Atlas/ &
    become_user: root