# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Compile
    displayName: Build Stage
    jobs: 
      - job: Build
        displayName: Build Angular
        steps:
          - task: NodeTool@0
            displayName: "Compiling Angular"
          - script:
              npm install -g @angular/cli
              npm install
              ng build --prod
      - job: TerraForm
        displayName: Artifact Teraform
        steps:
          - task: CopyFiles@2
            displayName: "Copy Terraform"
            inputs:
              SourceFolder: "./provision"
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              ArtifactName: drop
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              publishLocation: Container
              
  - stage: Provision_Environment
    displayName: Provision Env
    jobs: 
      - job: Provision
        displayName: Provision_Environment
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''Provision Environment Stage'''

  - stage: ReadinessTests
    displayName: Readiness Test
    jobs: 
      - job: Provision
        displayName: ReadinessTests
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''ReadinessTests Stage'''

  - stage: UnitTests
    displayName: Unit Test
    jobs: 
      - job: Provision
        displayName: UnitTests
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''Unit Tests Stage'''