# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Compile
    displayName: Build Stage
    jobs: 
      - job: Build
        displayName: Build
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''Build Stage'''
  - stage: Provision Environment
    displayName: Provision Environment Stage
    jobs: 
      - job: Provision
        displayName: Provision Environment
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''Provision Environment Stage'''
  - stage: ReadinessTests
    displayName: ReadinessTests Stage
    jobs: 
      - job: Provision
        displayName: ReadinessTests
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''ReadinessTests Stage'''
  - stage: UnitTests
    displayName: UnitTests Stage
    jobs: 
      - job: Provision
        displayName: UnitTests
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''UnitTests Stage'''