# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Compile
    displayName: Build Stage
    jobs: 
      - job: Build
        displayName: Build Angular
        steps:
          - task: NodeTool@0
            displayName: "Compiling Angular"
          - script:
              npm install -g @angular/cli
              npm install
              ng build --prod
      - job: TerraForm
        displayName: Artifact Teraform
        steps:
          - task: CopyFiles@2
            displayName: "Copy Terraform"
            inputs:
              SourceFolder: "./provision"
              TargetFolder: '$(Build.ArtifactStagingDirectory)/provision'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: provision'
            inputs:
              ArtifactName: provision
              PathtoPublish: $(Build.ArtifactStagingDirectory)/provision
              publishLocation: Container
      - job: TSpector
        displayName: TSpector Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - script: |
              npm install
              npm run tsc
            displayName: 'npm install and build'
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              SourceFolder: "./e2e"
              TargetFolder: '$(Build.ArtifactStagingDirectory)/e2e'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: TSpector'
            inputs:
              ArtifactName: e2e
              PathtoPublish: $(Build.ArtifactStagingDirectory)/e2e
              publishLocation: Container


  - stage: Provision_Environment
    displayName: Provision Env
    jobs: 
      - job: Provision
        displayName: Provision_Environment
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''Provision Environment Stage'''

  - stage: ReadinessTests
    displayName: Readiness Test
    jobs: 
      - job: Provision
        displayName: ReadinessTests
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''ReadinessTests Stage'''

  - stage: UnitTests
    displayName: Unit Test
    jobs: 
      - job: Provision
        displayName: UnitTests
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''Unit Tests Stage'''